### ISSUE TITLE
diff localizations

### ISSUE THREAD

**Issue by maniyax** [TifloDev/soundrts#4]
Сравнить /res/ui/tts.txt и /res/ui-ru/tts.txt

Добавить непереведенные номера в оригинальный режим.

Модами займемся позже, там с нуля много где придется адаптировать.

**Comment by cyrmax** [comment]
В res/ui-ru/tts.txt есть не переведённые номера. Их нужно перевести?

**Comment by maniyax** [comment]
Разве они остались там? Если да, то перевести.

Подскажи номера, пожалуйста.

**Comment by cyrmax** [comment]
Я допереводил то, что было не переведено и исправил то, что было явно кривым. 
Сделаю ПР, в нём смотри какие строки изменены и по ним узнаешь номера. Я слишком поздно увидел твоё сообщение и не выписал номера исправленных фраз.
